### Get all blogs
GET http://localhost:3001/api/blogs

### Create a new blog
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "Robert C. Martin",
  "url": "https://blog.cleancoder.com",
  "title": "Clean Code",
  "likes": 0
}

### Create another blog
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "Dan Abramov",
  "url": "https://overreacted.io",
  "title": "Things I Don’t Know as of 2018",
  "likes": 5
}

### Update likes - exercise 6
PUT http://localhost:3001/api/blogs/2
Content-Type: application/json

{
  "likes": 5
}

### Test error handler - missing url (required field) - exercise 7
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "Someone",
  "title": "No URL blog"
}

### Delete a blog (change id if needed), paste token from login
DELETE http://localhost:3001/api/blogs/1
Authorization: Bearer <token>

### Should fail - year too old
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer <your_token>

{
  "title": "Old blog",
  "author": "Someone",
  "url": "https://test.com",
  "year": 1990
}

###  Should fail - year in future
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer <your_token>

{
  "title": "Future blog",
  "author": "Someone",
  "url": "https://test.com",
  "year": 2099
}

### Should succeed
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer <your_token>

{
  "title": "Valid blog",
  "author": "Someone",
  "url": "https://test.com",
  "year": 2024
}